Improve handling of `xhprof_prepend.php`
tyler36/ddev-xhgui pull request #28
Opened 2024-04-26 04:01 UTC by tyler36

The default `xhpro_prepend.php` file that ships with recent flavors of DDEV is NOT compatible with this addon.

Currently, we take ownership of it so this addon can function. However, we don't return ownership. This could cause problems if the addon is removed or disabled.

This PR offers a different approach.

- use `post-start` hook to claim ownership.
- use `pre-stop` hook to return ownership.

This handles ownership while the addon is active.
But returns ownership when stop; thus DDEV will return to "default" state next time it checks the file.

Fixes #11

2024-04-26 11:26 UTC, deviantintegral approved these changes
Great idea! 👏

2024-04-27 16:44 UTC, rfay requested changes
Minor changes, suggesting `cp` if that is easy for you.

Overall, I'm still not even happy that we mount the prepend file and think we should be doing something better in DDEV rather than working around it. But here we are, so this approach is definitely an improvement.

2024-04-27 16:44 UTC, rfay commented on config.xhgui.yaml
> +      PHP
This line would be easier to understand if it were just the traditional `EOF` or maybe `PHP_EOF`. Caught me by surprise. Not that important of course.

2024-04-27 16:44 UTC, rfay commented on config.xhgui.yaml
> +      cat <<-PHP > .ddev/xhprof/xhprof_prepend.php
Wouldn't it be easier to use a `cp` here instead of cat? Then it's also one line.

2024-04-27 16:44 UTC, rfay commented on config.xhgui.yaml
> +      cat <<-PHP > .ddev/xhprof/xhprof_prepend.php
Same, wouldn't `cp` be easier?

2024-04-27 16:44 UTC, rfay commented on install.yaml
> -- xhprof/xhprof_prepend.php
If you use `cp` you'd still have this, it would just be indirectly installed.

2024-05-10 00:54 UTC, tyler36 commented
> Wouldn't it be easier to use a cp here instead of cat? Then it's also one line.

The idea here was to _avoid_ copying a file. I want to dynamically write out it.

Because the file contents contains `#ddev-generated` , I couldn't figure out how to escape the hash using `echo`.
Instead, I went with HEREDOC syntax. The output file contains documentation that makes it more understandable about what the file does and how it behaves.

If we went with `cp`, we would copy over a file (so we now how 2 files, our temp fake and the replace `xhprof_prepend.php`).
What about `pre-stop` hook? Writing `#ddev-generate` cause DDEV to replace the file with it's default on start up (see https://github.com/tyler36/ddev-xhgui/pull/29#issuecomment-2103641540) so we could keep it `pre-stop` here. 
I not sure about using `cp` here, would that be another file to copy over?

2024-05-28 00:16 UTC, rfay approved these changes
I think you should go ahead with this. It can be adjusted in the future.

Another technique is to use something like `#xhgui-generated` in the text of the prepend file, and feel free to delete it (using `removal_actions`) if it contains that. `if grep '#xhgui-generated' <phpfile>; then rm <phpfile>; fi`

2024-05-28 01:26 UTC, tyler36 commented
Rebased
.

2024-05-28 01:46 UTC, merged